Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
5*amp+10*volt
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mDimensionMismatchError[0m                    Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [38;5;241;43m5[39;49m[38;5;241;43m*[39;49m[43mamp[49m[38;5;241;43m+[39;49m[38;5;241;43m10[39;49m[38;5;241;43m*[39;49m[43mvolt[49m

File [0;32m/usr/local/lib/python3.11/site-packages/brian2/units/fundamentalunits.py:1422[0m, in [0;36mQuantity.__add__[0;34m(self, other)[0m
[1;32m   1421[0m [38;5;28;01mdef[39;00m [38;5;21m__add__[39m([38;5;28mself[39m, other):
[0;32m-> 1422[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_binary_operation[49m[43m([49m[43mother[49m[43m,[49m[43m [49m[43moperator[49m[38;5;241;43m.[39;49m[43madd[49m[43m,[49m
[1;32m   1423[0m [43m                                  [49m[43mfail_for_mismatch[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m
[1;32m   1424[0m [43m                                  [49m[43moperator_str[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m+[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/usr/local/lib/python3.11/site-packages/brian2/units/fundamentalunits.py:1362[0m, in [0;36mQuantity._binary_operation[0;34m(self, other, operation, dim_operation, fail_for_mismatch, operator_str, inplace)[0m
[1;32m   1359[0m     [38;5;28;01melse[39;00m:
[1;32m   1360[0m         message [38;5;241m=[39m ([38;5;124m'[39m[38;5;124mCannot calculate [39m[38;5;132;01m{value1}[39;00m[38;5;124m [39m[38;5;132;01m%s[39;00m[38;5;124m [39m[38;5;132;01m{value2}[39;00m[38;5;124m, units do not [39m[38;5;124m'[39m
[1;32m   1361[0m                    [38;5;124m'[39m[38;5;124mmatch[39m[38;5;124m'[39m) [38;5;241m%[39m operator_str
[0;32m-> 1362[0m         _, other_dim [38;5;241m=[39m [43mfail_for_dimension_mismatch[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mother[49m[43m,[49m[43m [49m[43mmessage[49m[43m,[49m
[1;32m   1363[0m [43m                                                   [49m[43mvalue1[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[43m,[49m
[1;32m   1364[0m [43m                                                   [49m[43mvalue2[49m[38;5;241;43m=[39;49m[43mother[49m[43m)[49m
[1;32m   1366[0m [38;5;28;01mif[39;00m other_dim [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1367[0m     other_dim [38;5;241m=[39m get_dimensions(other)

File [0;32m/usr/local/lib/python3.11/site-packages/brian2/units/fundamentalunits.py:188[0m, in [0;36mfail_for_dimension_mismatch[0;34m(obj1, obj2, error_message, **error_quantities)[0m
[1;32m    186[0m         [38;5;28;01mraise[39;00m DimensionMismatchError(error_message, dim1)
[1;32m    187[0m     [38;5;28;01melse[39;00m:
[0;32m--> 188[0m         [38;5;28;01mraise[39;00m DimensionMismatchError(error_message, dim1, dim2)
[1;32m    189[0m [38;5;28;01melse[39;00m:
[1;32m    190[0m     [38;5;28;01mreturn[39;00m dim1, dim2

[0;31mDimensionMismatchError[0m: Cannot calculate 5. A + 10. V, units do not match (units are A and V).
DimensionMismatchError: Cannot calculate 5. A + 10. V, units do not match (units are A and V).

